dependencies:
- name: zookeeper
  version: "1.2.3"
  repository: "file://charts/zookeeper"
- name: cassandra
  version: "1.2.3"
  repository: "file://charts/cassandra"
- name: solr
  version: "1.2.3"
  repository: "file://charts/solr"
