dependencies:
- name: cassandra
  version: "0.13.3"
  repository: "https://bjornm82.github.io/helm-charts/"
- name: solr
  version: "1.3.3"
  repository: "https://bjornm82.github.io/helm-charts/"
- alias: zookeeper-atlas
  name: zookeeper
  version: 2.1.3
  repository: "https://bjornm82.github.io/helm-charts/"
